package client;


import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.File;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Axel
 */
public class GUI extends javax.swing.JFrame {       
    String path,tmp_u="",tmp_m="";
    int bandera;
    String mensaje_inicio="",mensaje_medio="",mensaje_final="";
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        bandera=0;
        File f = new File("");
        String ruta = f.getAbsolutePath();
        path=ruta;
        mensaje_inicio= "<head><base href=\"file:"+ruta+"\\\">"+
                "<style>#usuarios {"+
                  "font-family: Arial, Helvetica, sans-serif;"+
                  "border-collapse: collapse;"+
                  "width: 100%;"+
                "} #usuarios td, #usuarios th {"+
                  "border: 0px solid #ddd;"+
                 " padding: 8px;"+
                "}#usuarios tr:nth-child(even){background-color: #f2f2f2;}"+
                "#usuarios tr:hover {background-color: #ddd;}"+
                "#usuarios th {"+
                 " padding-top: 12px;"+
                  "padding-bottom: 12px;"+
                  "text-align: left;"+
                  "background-color: #04AA6D;"+
                  "color: white;}"+
                "</style>"+
                "</head>"+ 
                "<table id=\"usuarios\">\n";
         /*   "  <tr>\n" +
            "    <th>Usuario</th>\n" +
            "    <th>Mensaje</th>\n" +
            "  </tr>";*/
       
       mensaje_final="</table>"; 
        
        ImageIcon foto_cara = new ImageIcon(ruta+"\\risa.gif");
        ImageIcon foto_wow = new ImageIcon(ruta+"\\wow.gif");
        //ImageIcon foto = new ImageIcon("C:\\Users\\52552\\Documents\\NetBeansProjects\\tttttttttt\\cara.gif");
        Icon icono_cara = new ImageIcon(foto_cara.getImage().getScaledInstance(jLabel4.getWidth(),jLabel4.getHeight(),Image.SCALE_DEFAULT));
        jLabel4.setIcon(icono_cara);
        Icon icono_wow = new ImageIcon(foto_wow.getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(),Image.SCALE_DEFAULT));
        jLabel2.setIcon(icono_wow);
        //jEditorPane1.setText(mensaje_inicio);
        //bandera=1;
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelDialog = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        fieldMessage = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        fieldUser = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        privateMessagesArea = new javax.swing.JTextArea();
        menssagePriv = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        usersOnline = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejemplo");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(400, 450));
        setSize(new java.awt.Dimension(1428, 1100));
        getContentPane().setLayout(null);

        panelDialog.setEditable(false);
        panelDialog.setContentType("text/html");
        jScrollPane1.setViewportView(panelDialog);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(21, 24, 275, 148);

        jLabel1.setText("Escribe aquí:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 280, 90, 16);
        getContentPane().add(fieldMessage);
        fieldMessage.setBounds(130, 270, 170, 30);

        sendButton.setText("Enviar");
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendButtonMouseClicked(evt);
            }
        });
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sendButton);
        sendButton.setBounds(310, 270, 72, 23);

        jLabel3.setDoubleBuffered(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 330, 0, 0);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 260, 292, 0);

        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 330, 60, 42);

        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 330, 60, 42);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(20, 380, 330, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(20, 310, 330, 3);

        jLabel5.setText("Usuario:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 230, 60, 16);
        getContentPane().add(fieldUser);
        fieldUser.setBounds(130, 220, 170, 30);

        privateMessagesArea.setColumns(20);
        privateMessagesArea.setRows(5);
        jScrollPane2.setViewportView(privateMessagesArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(320, 60, 234, 110);

        menssagePriv.setText("Mensajes Privados");
        getContentPane().add(menssagePriv);
        menssagePriv.setBounds(390, 30, 100, 16);

        usersOnline.setColumns(20);
        usersOnline.setRows(5);
        jScrollPane3.setViewportView(usersOnline);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(400, 200, 160, 200);

        jLabel6.setText("Usuarios Disponibles");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 180, 120, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendButtonActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.out.println("");
        tmp_u = fieldUser.getText();
        tmp_m = fieldMessage.getText();

        //C:\Users\Luis Velasco\OneDrive\Documentos\5to s escom\redes2\practicas\ChatP3\risa.gif
        //String respuesta = logica
              
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.out.println("<img src=\"risa.gif\"width=\"50\" height=\"50\"></img>");
               mensaje_medio= mensaje_medio+"  <tr>\n" +
            "    <td>"+fi   eldUser.getText()+" dice: </td>\n" +
            "    <td>"+"<img src=\"risa.gif\"width=\"50\" height=\"50\"></img>"+"</td>\n" +
            "  </tr>";
        panelDialog.setText(mensaje_inicio+mensaje_medio+mensaje_final);
        this.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.out.println("<img src=\"wow.gif\"width=\"40\" height=\"40\"></img>");
                       mensaje_medio= mensaje_medio+"  <tr>\n" +
            "    <td>"+fieldUser.getText()+" dice: </td>\n" +
            "    <td>"+"<img src=\"wow.gif\"width=\"40\" height=\"40\"></img>"+"</td>\n" +
            "  </tr>";
        panelDialog.setText(mensaje_inicio+mensaje_medio+mensaje_final);
        this.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void sendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseClicked
        tmp_u =  fieldUser.getText();
        tmp_m =  fieldMessage.getText();
        mensaje_medio= mensaje_medio+"  <tr>\n" +
            "    <td>"+fieldUser.getText()+" dice: </td>\n" +
            "    <td>"+fieldMessage.getText()+"</td>\n" +
            "  </tr>";
        panelDialog.setText(mensaje_inicio+mensaje_medio+mensaje_final);

        this.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_sendButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldMessage;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel menssagePriv;
    private javax.swing.JEditorPane panelDialog;
    private javax.swing.JTextArea privateMessagesArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextArea usersOnline;
    // End of variables declaration//GEN-END:variables
}
